### ISSUE TITLE
jsxstyle like API on top of styletron

### ISSUE THREAD

**Issue by andersekdahl** [styletron/styletron#138]
Hi!
First off, many thanks for making styletron!

I'd like to look into creating a jsxstyle like API on top of styletron. That is, being able to write:
```
<Block textAlign="center">...</Block>
```

Creating styled components outside of a render function makes sense a lot of the time but it's also really nice to be able to colocate styling and markup in some cases.

So I'd like to take a look at implementing this in styletron but I wanted to open this issue first to discuss it.

I'm using React so I'd probably implement it in `styletron-react`, but perhaps it could be generalized so that `styletron-preact` etc can use it as well?

**Comment by faddee** [comment]
This is a great idea and fairly easy to do. It would be a nice supplement to `styled` when you e.g. only need a single rule:

```jsx
import React from 'react';
import {styled, Block} from 'styletron-react';

const Item = styled('div', {
  /* lots of style */
});

function MyComponent(props) {
  return (
    <Block display="flex">
      {props.items.map(data => <Item {...data} />)}
    </Block>
  );
}
```

The hard part would be to make `Block` compatible with `styled`:

```jsx
import React from 'react';
import {styled, Block} from 'styletron-react';

const H1 = styled('h1', {
  fontFamily: 'sans-serif',
});

function MyComponent(props) {
  return (
    <Block fontFamily="serif" component={H1}>This may not be `serif`</Block>
  );
}
```

There should be a way of solving this but `Block` would need to handle `styled` components differently than other components.

**Comment by andersekdahl** [comment]
I'm not sure that I feel like that's a problem. If you pass `component={H1}` I think the developer would assume that `H1` would be the inner component. So if both tries to set `fontFamily` the most inner component would win. Which is the same if you're using `styled()`. If you want to be able to override it you'd change it to:
```
const H1 = styled('h1', (props) => ({
  fontFamily: props.fontFamily || 'sans-serif',
}));
```

Or did I missunderstand you?

**Comment by faddee** [comment]
That would completely bloat the inner components, don't you think? That was just a simple example, but it isn't always that easy in larger projects with multiple developers. If not to mention the typing nightmare that would cause when not using a string as inner-inner component.

It would be nice if the user doesn't need to keep knowledge of the styling in the inner components and still feel comfortable of using both tools together.

But I guess that would require some kind of changes to the `core` function. Maybe pass the resolved style to the inner styled component with a secret prop (maybe not the most elegant)?

```js
function Base(props) {
  const restProps = assign({}, props);
  delete restProps.component;
  delete restProps.children;
  return React.createElement(props.component || 'div', restProps, props.children);
}

function emitStyle(props) {
  const style = assign({}, props);
  delete style.component;
  delete style.children;
  return style;
}

function assignProps(styletron, styleResult, ownProps) {
  const passProps = {
    component: ownProps.component,
    children: ownProps.children,
  };

  if (/* detect if `ownProps.component` is a styled component */) {
    /* somehow make `ownProps.component` resolve `styleResult` instead */
    return passProps;
  } else {
    passProps.className = injectStylePrefixed(styletron, styleResult);
    return passProps;
  }
}

const Block = core(Base, emitStyle, assignProps);
```

**Comment by rtsao** [comment]
This can can certainly be done with `styletron-engine-atomic`, but having first-class support for a completely different API using props is probably out of scope given this project is opinionated towards the use of style objects.
