### ISSUE TITLE
Integrating bundlesize 

### ISSUE THREAD

**Issue by siddharthkp** [styletron/styletron#154]
@rtsao Hey, thanks for building styletron.

I'm having troubling navigating through the repository.

Do I add tests to each of the packages? (and as many statuses) or should I just add it in one place?

**Comment by rtsao** [comment]
That's a good question! I'm thinking separate statuses for each package might make the most sense.

**Comment by tajo** [comment]
Can we just add https://bundlephobia.com/ badge to every package.json? Or something more fancy as a part of the build pipeline? Or not relevant anymore and closing this issue?

**Comment by siddharthkp** [comment]
Wow this issue is old! I'm going to close this now
