### ISSUE TITLE
create jest-styletron similar to (and for the same reasons as) jest-styled-components

### ISSUE THREAD

**Issue by koulmomo** [styletron/styletron#176]
When running jest snapshot tests against styletron styled components, we encounter the same issues as what happened when people tried doing the same with [styled-components](https://www.styled-components.com/) (see: https://github.com/styled-components/jest-styled-components/issues/29).

**Comment by clayne11** [comment]
This solution didn't work for me. I think the correct solution is to create a custom serializer for Jest that filters out the `$theme` and some of the other internal props.

**Comment by tajo** [comment]
I think we can elegantly solve this by using the [No-op engine](https://github.com/styletron/styletron/issues/256) for testing. 

If you use the real engine, we can assume that you actually want to snapshot classNames / styles and you are fine with (possibly) frequent updates. Also, the `jest-styled-components` issue mentions problems when using Button across multiple components causing massive churn in snapshot tests. That can be solved by using shallowRendering when taking snapshots.
