### ISSUE TITLE
Cannot use 'new' with an expression whose type lacks a call or construct signature.

### ISSUE THREAD

**Issue by drejohnson** [styletron/styletron#185]
Following the docs for using `styletron-server` gives constructor error. Using v3.0.0-rc.3

```
import * as Styletron from 'styletron-server';
const styletron = new Styletron()
```

And I get `TypeError: styletron_server_1.default is not a constructor` if I import like so
```
import Styletron from 'styletron-server';
const styletron = new Styletron()
```

**Comment by rtsao** [comment]
This functionality now lives in `styletron-engine-atomic` so I think this isn't relevant anymore.
