### ISSUE TITLE
[Question] Is there a way to generate a separate .css stylesheet file?

### ISSUE THREAD

**Issue by chinchang** [styletron/styletron#193]
@rtsao Possible to configure Styletron to generate a separate CSS file or inlining styles is the only option?

**Comment by frenic** [comment]
It's the only option at this point. You wouldn't benifit of having it as an external style sheet since you can dynamically change the style and therefore you would very likely loose long term caching.

**Comment by rtsao** [comment]
See: https://github.com/styletron/styletron/issues/268#issuecomment-417186969
