### ISSUE TITLE
Style declarations with !important are treated as duplicates by Styletron

### ISSUE THREAD

**Issue by bzalasky** [styletron/styletron#216]
I'm working on a project that uses React components inside a legacy Backbone application that uses Bootstrap. Bootstrap include some obnoxious print styles like this:

    @media print {
      *, *:before, *:after { color: black !important; }
    }

In this application components have a default theme, as well as a report/print theme (that's primarily used when a user saves to PDF, so we want to keep colors). I'd prefer not to use !important for the default theme's color styles (in case we wanted to override them for some reason). When I set a report/print specific color style with important (with or without the print media query), Styletron treats the declaration as a duplicate and sticks with the non !important version. Is this expected behavior?

I'm able to work around this by adding an override with a css class, but it'd be nice to take care of it with Styletron.

**Comment by bzalasky** [comment]
Would this be a case where non-atomic rendering would be desirable? We've since worked around this by customizing our Bootstrap build to exclude print styles.

**Comment by rtsao** [comment]
Feel free to re-open this if this is still an issue.

That said, I think `!important` is pretty wonky in the context of style objects. I would probably not consider that to really be supported.
