### ISSUE TITLE
Feature request: withProps

### ISSUE THREAD

**Issue by kahwee** [styletron/styletron#224]
## Background

I wrote a generic box component in Styletron that looks like this:

```
      <Box $mt={2} $pv={3}>
        Hello!
      </Box>
```

In the above example `$mt` refers to to `marginTop` and `{2}` is an index that would be returning `1.5rem`. `$pv` is a shorthand of `paddingTop` and `paddingBottom`.

I wanted to reuse the code of Box component such that I can have a `BaseButton`

I tried to do:

```
export const BaseButton = withStyle(Box, {
  $pv: 3,
  borderRadius: '4px',
  textDecoration: 'none'
});
```

In the above example my `BaseButton` will now have `$pv: 3`, overwriting `Box`'s default `$pv`. I also want `BaseButton` to inherit the possible properties of `Box`. It is currently not possible with `withStyle` or `withTransform`.

## Proposal

Can we have `withProps` such that I can do:

```
export const BaseButton = withStyle(withProps(Box, {
  $pv: 3
}), {
  borderRadius: '4px',
  textDecoration: 'none'
});
```

It could be worth it to do `compose` where we can express the above like this:

```
const enhance = compose(
  // These are both single-argument HOCs
  withProps({$as: 'button', $pv: 4}),
  withStyle({marginTop: '1px'})
)
const EnhancedComponent = enhance(Box)
```

The above however could represent a breaking change.

**Comment by jbellsey** [comment]
I think this request may not really be styletron-related. Have a look at [recompose](https://github.com/acdlite/recompose), which offers many such composable utilities:

```js
import {defaultProps} from 'recompose';

export const BaseButton = defaultProps({
  $pv: 3
})(withStyle(Box, {
  borderRadius: '4px',
  textDecoration: 'none'
});
```
