### ISSUE TITLE
styletron-inferno.js examples not working with inferno 5

### ISSUE THREAD

**Issue by caracal7** [styletron/styletron#225]
[Error] TypeError: type is not a function. (In 'type(props, context)', 'type' is "div")
	mountComponent (index.js:9410)
	mountComponent (index.js:9412)
	mountComponent (index.js:9405)
	render (index.js:10232)
	update (index.js:20735)
	./src/index.js (index.js:20741)

**Comment by rtsao** [comment]
See: https://github.com/styletron/styletron/issues/147#issuecomment-417187655
