### ISSUE TITLE
Use csstype as a dependency 

### ISSUE THREAD

**Issue by frenic** [styletron/styletron#228]
A lot has happen since you copyed it. Bugs has been fixed and a lot of properties has been added. And more features and updates are coming. Using it as a dependency would be beneficial instead of updating the types by hand.

If it doesn't work, I would like to know why?

Another thought: In TypeScript-world libraries sees csstype as an ability to provide closed typings for style. I know it's not default in Flow. But you're able to do it using the `$Exact` and `$Shape` utility. I can't see whether you already use this or not. Hade a look in the [type check file at csstype](https://github.com/frenic/csstype/blob/master/typecheck.js) for examples. But maybe this isn't the way to go for Flow users?

**Comment by rtsao** [comment]
Yeah, I'm working on migrating over; I definitely want to get rid of all the vendored code.

The times when I've tried switching over, for some reason Flow seems to hang -- I'm still not entirely sure what's going on, but I suspect it might have to do with just how many types there were in the exported file. When I deleted all the unused type definitions (e.g. hyphenated properties, etc), it seemed to work. It seems weird that this would make any difference, but I wonder if the sheer amount of types is overwhelming the flow server.

**Comment by frenic** [comment]
Oh, that's weird. I mean, defining all the DOM APIs and that kind of stuff should be even more. Could it have anything to do with the file size? It's over 200KB+. I could provide csstype with a split version of the Flow types if performance is an issue. But I would like to be sure that it isn't a recursion issue or something like that first.

**Comment by rtsao** [comment]
Just documenting here the reason csstype was vendored. Things may have changed with newer versions of Flow, however.

- Generics for length type seemed to cause breakages. Removing the generics (e.g. length type) resolved the problem.
- All the unused Flow types seemed to overwhelm Flow (it would basically just behave like `any`). Deleting the unused permutations resolved the issue.

We should upstream these potentially.
