### ISSUE TITLE
Support refs via React 16.3 forwardRef

### ISSUE THREAD

**Issue by schnerd** [styletron/styletron#253]
Styletron supports refs via the special `$ref` prop to get direct access to the html element. However, it would be awesome if it used the normal `ref` prop so that styled components can be used more interchangeably with normal html elements.

An example of where this would be useful is a tooltip component:
```js
<Tooltip content="hello">
    <span>hover me</span>
</Tooltip>
```

`<Tooltip>` has some magic where it adds a `ref` prop to the `<span>` (via cloneElement)–it needs the ref for dom positioning purposes. However, if the child is a styled element this stops working:

```js
<Tooltip content="hello">
    <StyledSpan>hover me</StyledSpan>
</Tooltip>
```

> Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail

Making styletron use [React.forwardRef](https://reactjs.org/docs/forwarding-refs.html) internally would smooth this out a bit.

**Comment by rtsao** [comment]
This would be great. I think the only reason this hasn't been done in the React package is technically React <16.3 support hasn't been dropped yet and I wanted to land some more features before doing a breaking change.

But those things have been done, so I think there's no remaining blockers for dropping support version support!

**Comment by tajo** [comment]
Can we add support for `forwardRefs` in v4 and keep `$ref` around as a deprecated (throwing warning) feature that will be removed in v5? Should work? Also, the v5 transition should be as simple as find&replace all `$ref` -> `ref`.

**Comment by tajo** [comment]
Actually, we should just do v5 since we can drop the support for older Reacts and also remove `create-react-context`.

**Comment by chasestarr** [comment]
pr for this has been merged to master: https://github.com/styletron/styletron/pull/309
