### ISSUE TITLE
Feature request: Styletron engine/renderer for React Native

### ISSUE THREAD

**Issue by digitalmaster** [styletron/styletron#26]
The state of managing css in React-Native is still kinda clunky. This would be a huge improvement.. 

Do you know if it's supported?

**Comment by rtsao** [comment]
As someone who hasn't actually had a chance to use React Native myself, I'm interested to learn more about which parts of Styletron could help! I don't know much about it, to be honest!

In my mind, the coolest thing about Styletron is the under-the-hood mapping of declarations to atomic classes, with the result of producing tiny stylesheets for server-rendering for browsers -- I wouldn't be able to say how that transfers into the context of React Native.

**Comment by ads1018** [comment]
React Native support would be awesome! I know styled-components support its -> https://github.com/styled-components/styled-components#react-native

**Comment by faddee** [comment]
Haven't got a chance to work with React Native so I'm not that familiar of what's happening under the hood but shouldn't this work?

```jsx
function styled(Base, style) {
  return (props) => (
    <Base
      {...props}
      style={{
        ...(typeof style === 'function' ? style(props) : style),
        ...props.style
      }}
    />
  );
}
```

With of course some minor tweaks so you're able to compose styled components.

**Comment by IljaDaderko** [comment]
Any updates on react-native support / implementation examples?

**Comment by rtsao** [comment]
With the new v4 architecture, all that needs to be done here is a rendering engine for react native (which uses RN-shaped style objects). There's no assumptions about atomic rendering or even the shape of style objects.

**Comment by louisgv** [comment]
Is this issue resolved? If not I can take a whack at it this week

**Comment by tajo** [comment]
> Is this issue resolved?

It's not. We don't use RN.

> If not I can take a whack at it this week

That would be great!

**Comment by jachiike-madubuko** [comment]
Very excited to see this extension of styletron. Is there any news for 2020 on progress. Thanks for being badass!

**Comment by tajo** [comment]
@jachiike-madubuko We still don't have any plans for RN engine since we don't use RN.

**Comment by Stringsaeed** [comment]
anyone work on this or should work on it?

**Comment by tajo** [comment]
@Stringsaeed No. The status is unchanged.
