### ISSUE TITLE
Missing Typescript definitions 

### ISSUE THREAD

**Issue by MargaretKrutikova** [styletron/styletron#273]
Typescript definitions are missing from all packages in the latest versions, seems like they disappeared somewhere on the way from `v3` to `v4`, because they were added again in `3.0.1` according to [this issue](https://github.com/styletron/styletron/issues/205). Is there any way they can be included in the latest `v4` release?

**Comment by frenic** [comment]
I stopped maintaining the TypeScript definitions after I moved to another styling library and didn't have the time to adopt them. So they were removed when they became out of sync with the new api. It would be better suited to have them at DefinitelyTyped if someone would like to create them again.

**Comment by tajo** [comment]
We don't currently use Typescript in our projects. It might change in the future but until then we are not planning to build official TS definitions.

> It would be better suited to have them at DefinitelyTyped if someone would like to create them again.

+1, that would great!
