### ISSUE TITLE
Missing flow property

### ISSUE THREAD

**Issue by ardok** [styletron/styletron#277]
https://github.com/styletron/styletron/blob/master/packages/styletron-standard/src/style-types.js#L1218

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
```
justify-content: start;      /* Pack items from the start */
justify-content: end;        /* Pack items from the end */
justify-content: left;       /* Pack items from the left */
justify-content: right;      /* Pack items from the right */
justify-content: stretch; 
justify-content: safe center;
justify-content: unsafe center;
```

**Comment by frenic** [comment]
The types should be updated with the latest from https://github.com/frenic/csstype/blob/master/index.js.flow. Probably more properties missing since it was last updated.
