### ISSUE TITLE
Allow to omit provider in unit tests

### ISSUE THREAD

**Issue by slonoed** [styletron/styletron#278]
Right now styled components always require Provider context. It doesn't make a lot of sense when doing unit testing.

Right now I'm using this
```
const mount = element => {
  const wrapper = enzyme.mount(r(StyletronProvider, {value: new Styletron()}, element))
  return wrapper.childAt(0)
}
```

Which is add unnecessary wrapper in code.

Would be nice to have a way to specify options to ignore provider beeing undefined.

**Comment by rtsao** [comment]
Yeah, agreed this is a good idea. See: https://github.com/styletron/styletron/issues/256 The next major version will have a no-op provider by default so this can be omitted in tests.

**Comment by slonoed** [comment]
@rtsao does it really require major version? I'm not familiar with codebase, just asking.

**Comment by slonoed** [comment]
I found an OK workaround. In case someone uses Jest:

```
jest.setMock('styletron-react', {
  styled: (Component, styles) => {
    const Wrapper = ({children, ...props}) => r(Component, props, children)
    Wrapper.displayName = 'StyledElement'

    return Wrapper
  },
})
```
