### ISSUE TITLE
Poor type error messaging resulting from polymorphic styling arguments

### ISSUE THREAD

**Issue by rtsao** [styletron/styletron#283]
Because `styled`, `withStyle`, etc. accept both style objects and functions that return style objects as the second argument, Flow doesn't know which branch to pick when the type is incorrect.

This yields poor error messages, especially because Flow will only show one branch, which may not be relevant. To show the relevant branch, `--show-all-branches` must be used.

But ultimately, this is a rather poor experience.

One possible solution adding monomorphic equivalents so Flow can produce better type errors. 

This would look something like:

```js

// Only accepts static style objects
const Foo = styledStatic("div", {color: "red"});

// Only accepts style object functions
const Bar = styled("div", ({$color}) => ({color: $color}));
```

**Comment by tajo** [comment]
I would rather promote the future usage of `useStyletron` hook which will not have this issue. Breaking the `styled` API just to marginally improve the types seems not worth it?

**Comment by rtsao** [comment]
Agreed, a breaking change is probably unwise, but potentially `styledStatic` could be added as an extra alias for the same code (but without type polymorphism) so it could be opt-in (at least initially).

But it might not be worth the effort if a hook-based API became preferred.

**Comment by tajo** [comment]
Alright, let's close this issue for now and we'll see how the hook API goes. We can revisit later. Unless it's a pain point for many people right now?

**Comment by rtsao** [comment]
After some trial and error, I was able to make some slight progress using slightly simplified types (but using csstype directly).

In Flow 0.115, the following yields poor error messages for invalid style objects (i.e. irrelevant branches masking the real error):
```jsx
declare function styled(string, StyleObject): number;
declare function styled(string, void => StyleObject): number;

// or

// This is currently how styled is defined.
declare var styled = {
  (string, StyleObject): number,
  (string, void => StyleObject): number,
};
```

However, the following seems to work (invalid style objects yield useful error messages):

```jsx
type Styler =
  | StyleObject
  | void => StyleObject;

declare function styled(string, Styler): number;
```

So it seems avoiding direct polymorphism in the function signature by hoisting the style parameter type into a disjoint union seems to allow Flow to refine this correctly.

The actual HOC types are bit more complex, but I think this approach might work for us.
