### ISSUE TITLE
Provide an option to remove props from generated `div`

### ISSUE THREAD

**Issue by shanshanzhu** [styletron/styletron#291]
Provide an option to remove props from generated `element`

Example:
In this following code example
```
export const Wrapper = styled<{|
  color: string,
  children: Node,
|}>('div', props => {
  return {
    backgroundColor: props.color,
  };
});

export const Test = (props) => (
  <Wrapper color="#fff" {...props}>
    <p > test </p>
  </Wrapper>
);

```

Inspect The html element for Test, we will see what correspond to the wrapper as

`<div color="#fff" className="xxxx">`

Expected Results:
Provided a way so that color can be removed from generated div
`<div className="xxxx">`

If it is already possible, please help point me to the document

**Comment by rtsao** [comment]
See the built-in prop filtering functionality: https://github.com/styletron/styletron/tree/master/packages/styletron-react#styled-prop-filtering
