### ISSUE TITLE
Add display name as class name in development

### ISSUE THREAD

**Issue by clayne11** [styletron/styletron#294]
The Babel plugin is nice in that it adds the display name in the React dev tools but it would be very helpful to add the display name as a class as well for the HTML dev tools. `styled-components` does this and it's very nice for development.

**Comment by chasestarr** [comment]
does styletron's [browser debug mode](https://styletron.netlify.com/api/#browser-debug-mode) accomplish what your're looking for?

**Comment by clayne11** [comment]
Not exactly. It's very helpful to be able to look at the HTML tree and see an overview of which components are rendered which relative to their display name. It would be great if `styletron-react` could behave exactly how `styled-components` does.

**Comment by chasestarr** [comment]
I think this highlights the key difference between styletron and s-c. Styletron splits the classes you define into atomic classes each with a single property/value. Since a single class may be shared across multiple elements, it can't simply prepend a display name to the class name. Seeing a class name `MyButton-d7` on an unrelated element is misleading. There may be alternative ways to improve DOM inspection, but following styled-components' approach would not be practical.

**Comment by clayne11** [comment]
Why not simply add an additional class to every component that maps to its display name but isn't associated with any style rules? This is purely to make visual inspection and debugging easier.

**Comment by chasestarr** [comment]
Can we agree that this sort of feature should not be present in production builds? It would unnecessarily bloat the file size on page download. Understanding that, my main concern is we would provide an easy 'handle' for developers to select an element from the DOM that can't be relied on in practice. A huge boon to developer experience is that I don't need to care about how styletron creates atomic classes, but I reap the perf benefits.

As a react developer or any other user of styletron, I can apply my own custom class name to a component. Maybe you can look into a transform that would accomplish what you're looking for  outside of styletron?

```jsx
const MyButton = () => <button className="MyButton-debug">click</button>;
```

**Comment by clayne11** [comment]
This would definitely only be used in development.

Does this not sound like a useful feature to you? Having used `styled-components` extensively in the past this is one of the features I miss the most working with `styletron`. Being able to quickly identify which HTML element maps to which component speeds up the style debugging process pretty significantly.

**Comment by chasestarr** [comment]
I do think it would be a useful feature, but don't know how to mitigate the potential pitfalls. Open to suggestions

**Comment by clayne11** [comment]
I'm not really following along with what the pitfalls are. `styled-components` does this in a really nice way where during development you can easily inspect the DOM and every component has a class associated with the display name it's rendered from. These classes are purely for development and don't attach any styles to the component.

When `styletron` is attaching classes, we just need to look at the display name of the component and add an additional class with no styles associated it. For example:

```typescript
const Root = styled('div')
const Inner = styled('div')

const Thingy = () => (
  <Root>
    <Inner />
  </Root>
)
```

When rendered, would output something like this:

```html
<div class="Thingy__Root __debug 00 ab ts">
  <div class="Thingy__Inner __debug 11 gt as"></div>
</div>
```

The classes `Thingy__Root` and `Thingy__Inner` wouldn't have any styles associated with them, they're purely for helping a dev track down which components are rendering where to quickly debug issues.

I've found this incredibly helpful when using `styled-components` and it would be great to have in `styletron` as well.

Does that make sense or am I missing something?

**Comment by tajo** [comment]
I get the usefulness of this feature. However, it can't be implemented only with Babel. We would also have to introduce a new `styled` API (something like `withConfig` in styled-components). Also, it could be confusing to get a different output when comparing the dev and production. I think it's not worth the effort at this time and we should rather focus on: https://github.com/styletron/styletron/pull/111

**Comment by clayne11** [comment]
I've never used `withConfig` in `styled-components` and I'm getting this behavior out of the box.

**Comment by devdoomari3** [comment]
@tajo agreed -- the way styletron optimizes stuff here may require creating another browser-addon
(maybe extending chrome's inspector-panel can do the job?)

Also, it would be really nice if we can have "debug-only names" for a style definition.
(I'm not keen on using styled-components approach ---  it forces 1 style == 1 component, which makes mixing multiple styles difficult)
