### ISSUE TITLE
getting started with react docs

### ISSUE THREAD

**Issue by zsobral** [styletron/styletron#322]
I was reading the docs, and I think i found a typo

https://www.styletron.org/getting-started/#with-react

should be?

```diff
- import { Provider as StyletronProvider } from "styletron-react";
+ import { Provider as StyletronProvider, DebugEngine } from "styletron-react";
- import { Client as Styletron, DebugEngine } from "styletron-engine-atomic";
+ import { Client as Styletron } from "styletron-engine-atomic";
```

**Comment by tajo** [comment]
Good catch! Would you mind to open a PR [here](https://github.com/styletron/styletron.org)?

**Comment by zsobral** [comment]
np, https://github.com/styletron/styletron.org/pull/9
