### ISSUE TITLE
styletron-engine-atomic doesn't support undefined styles

### ISSUE THREAD

**Issue by erictaylor** [styletron/styletron#329]
<img width="838" alt="Screen Shot 2019-07-03 at 9 40 22 AM" src="https://user-images.githubusercontent.com/637924/60605598-10cc3c00-9d77-11e9-8db5-f5b2d4c5134a.png">

When attempting to write a style where the value is `undefined` I get an error like above. Using `null` instead of `undefined` works, but I'm not sure why `undefined` is handled any differently than `null`.

The TypeScript definitions use `csstypes` to type the `StyleObject` type, which means that according to the TypeScript definitions `null` is not valid where `undefined` is.

I'm pretty sure the Flow definitions have been updated to use `csstypes` directly once again, so I would imagine that `null` would also provide a type error in that case as well?

`renderStyle` gets called [here](https://github.com/styletron/styletron/blob/master/packages/styletron-engine-atomic/src/client/client.js#L209), which in turn calls `injectStylePrefixed` which has a call to `validateValueType` [here](https://github.com/styletron/styletron/blob/ed02c1e05665aaf865440354aa3747a1db7fe658/packages/styletron-engine-atomic/src/inject-style-prefixed.js#L27). `validateValueType` is what [throws the error](https://github.com/styletron/styletron/blob/ed02c1e05665aaf865440354aa3747a1db7fe658/packages/styletron-engine-atomic/src/inject-style-prefixed.js#L115).

I'll look into trying to submit a PR to address this, but if anyone has any insight I'd appreciate any feedback.

**Comment by tajo** [comment]
I would not mind supporting `undefined`, it would make writing some code easier. I guess the argument for not allowing `undefined` is preventing silent unintended errors. If you fat-finger the variable name, you would never know about it if it's just stripped and not apparent on the page.

Also, other CSS in JS libs also allow `undefined` (styled-components, emotion, fela).

cc @rtsao

**Comment by erictaylor** [comment]
PR #330

**Comment by rtsao** [comment]
We should support `undefined` because we can't statically prevent them.

```js
type StyleObject = {| foo?: number |};

const a : StyleObject = {foo: void 0};
const b : StyleObject = {};

// Equally valid with Flow
```

**Comment by rtsao** [comment]
Fixed by https://github.com/styletron/styletron/pull/330
