### ISSUE TITLE
[styletron-engine-atomic] MutationObserver unable to detect stylesheet changes

### ISSUE THREAD

**Issue by VladimirMilenko** [styletron/styletron#333]
Styletron engine atomic uses `CSSStyleSheet` to store CSS rules. Unfortunately, mutation of CSS rules via CSSStyleSheet.insertRule doesn't change DOM and therefore MutationObserver cannot track the changes.

A possible use case for this data: session replay via Logrocket/RRweb which are capturing events and dom mutation observers.

One way to make `sheet` changes reflecting in the dom is by using Proxy and inserting styles into DOM:

```js
 const handler = {
      apply: function apply(target, thisArg, argumentsList) {
        const result = target.apply(thisArg, argumentsList);
        styleRoot.innerHTML = Array.from(thisArg.rules, x => x.cssText).join('\n');

        styleRoot.sheet.insertRule = new Proxy(styleRoot.sheet.insertRule, handler); // otherwise proxy handler won't be called.

        return result;
      }
    };
    const proxy = new Proxy(styleRoot.sheet.insertRule, handler);
    styleRoot.sheet.insertRule = proxy;
    styleRoot.sheet.insertRule('.rr_track_on {}');
```

This is costly in terms of performance as your styles growths - more computation will be required.

In case of this logging, we can adjust the changes to not only work in a way of restoring DOM changes, but at least record insertions into a stylesheet.
This can be done in also multiple ways:
1. Proxy insert rule as on top
2. Add onNewRule hook for styletron engine.

The first option doesn't look that nice, since styletron doesn't mark created `style` node as styletron style cache, so, you're unable to track which node is created by styletron and which is not. Another solution for that - is to pass container for style, but that's extra configuration and still requires a proxy solution.

The second option, however, will add flexibility for listening to new rule additions.

## Proposed API
```js
const engine = new AtomicEngine({onNewRule: (rule, ruleIndex) => { }, prefix, etc})
```

**Comment by tajo** [comment]
Having `onNewRule` seems like a small / safe addition?

wdyt @rtsao?

**Comment by rtsao** [comment]
With the current implementation, I think you can do this:

```js

const engine = new StyletronClient();

const original = engine.styleCache.onNewValue;
engine.styleCache.onNewValue = (...args) => {
  // Do something here
  return original(...args);
}
// Same thing for `keyframesCache` and `fontFaceCache` if you care about those styles
```

Taking a step back, I'm curious to hear more about the use case(s) for this.

**Comment by rtsao** [comment]
I think the above is probably the best approach. Closing for now unless there's something special with the use case.
