### ISSUE TITLE
Feature request: Export StyleObject in styletron-react

### ISSUE THREAD

**Issue by phou87** [styletron/styletron#341]
We use a lot of custom styles in our codebase, and as a result end up passing style objects to components (primarily BaseUI components) a lot. Right now, we type these objects with our own custom type, but it'd be nice to be able to use StyleObject instead.

We could import it from styletron-standard, but we'd ideally not want to add a direct dependency on that package since it would be literally the only thing we're using.

**Comment by chasestarr** [comment]
Could you provide an example? Does the pattern below not infer the type as-expected? 

```js
const customStyle = {
  color: 'blue',
  fontSize: '10px',
};

const A = styled('div', customStyle);
```

**Comment by phou87** [comment]
It's moreso when we're making our own components customizable via style props.

```
import {Button} from 'baseui/button';

type Props = {
  style?: StyleObject,
};

function MyComponent(props) {
  return (
    <Button
      style={{...props.style, marginLeft: '16px'}}
    />
  );
}
```

**Comment by chasestarr** [comment]
I generally don't recommend allowing arbitrary styles provided to a component and initially defer towards defining a more restrained interface. Doing so would make it easier to edit the internal details of your component definition without the risk of adversely affecting instances of it.

Recommendations aside, I believe this is a fine addition to the `styletron-react` package. It already relies on the `StyleObject` in it's public interface and any breaking change introduced to `styletron-standard` requires a major bump in `styletron-react` as well.
