### ISSUE TITLE
Styletron warning using nextjs dynamic app layouts

### ISSUE THREAD

**Issue by matchatype** [styletron/styletron#367]
Styletron will produce a warning while in development, if you implement the dynamic layout technique described in the `with-dynamic-app-layout` [example](https://github.com/vercel/next.js/blob/canary/examples/with-dynamic-app-layout).

Here's a [minimal reproduction](https://codesandbox.io/s/bold-brahmagupta-l2ezp?file=/pages/index.js) for the issue, run it and check the console:

```
Warning: Expected server HTML to contain a matching <main> in <div>.
    in main (at BlueLayout.js:2)
    in BlueLayout (at _app.js:13)
    in DevProvider (at _app.js:12)
    in MyApp
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
```

**Comment by message** [comment]
It has nothing to do with styletron. On initial server side render `Component.Layout` is undefined.

**Comment by matchatype** [comment]
`<Component>.Layout` is always defined: `const Layout = Component.Layout || Noop`. Additionally, the official example, which the reproduction simply extends, by adding support for Styletron, works perfectly fine. It is only with the addition of Styletron that the issue surfaces.

**Comment by message** [comment]
Change your `_document.js`. Method  `getInitialProps` should look something like

```js
static async getInitialProps(ctx) {
	const originalRenderPage = ctx.renderPage;

	ctx.renderPage = () => originalRenderPage({
		enhanceApp: (App) => (props) => <StyletronProvider value={styletron}><App {...props} /></StyletronProvider>,
	});

	const initialProps = await Document.getInitialProps(ctx);

	const stylesheets = styletron.getStylesheets() || [];

	return {...initialProps, stylesheets};
}
```

**Comment by matchatype** [comment]
That works well, thank you! Is there any reference to this kind of setup?

**Comment by matchatype** [comment]
Unfortunately this setup conflicts with some BaseUI components like Modal, returning errors like the following:

```
Warning: Prop `className` did not match. Server: "b1 af ah b2 b3" Client: "b4 b5 b6 b2 b3"
```

**Comment by matchatype** [comment]
My bad. I had a wrong import statement that was causing that error. The fix is working indeed, thanks again!
The question remains: Is there any reference to this kind of setup?

**Comment by message** [comment]
There not. I adapted that from `styled-components`
