### ISSUE TITLE
Do you prefer hooks?

### ISSUE THREAD

**Issue by IRediTOTO** [styletron/styletron#382]
```
// Do you prefer hooks?
import { useStyletron } from "styletron-react";
const [css] = useStyletron();
<a className={css({ color: "red" })} href="/foo">
  Hello
</a>;
```
Hi. i don't like hook like this :D I must write it in many components, many pages...
I hope for something like this :D 
```
import { css} from "styletron-react";

<a className={css({ color: "red" })} href="/foo">
  Hello
</a>;
```
Yep, just that :D

**Comment by LXSMNSYC** [comment]
You may use [renderStyle](https://www.styletron.org/api-reference#renderstylestyle-string), which requires a Styletron engine instance.

**Comment by tajo** [comment]
You could import the engine instance directly but without some functionality like [debugging tools](https://www.styletron.org/api-reference#browser-debug-mode).

**Comment by chasestarr** [comment]
Closing, I believe there have been some other suggestions provided to the original comment
