### ISSUE TITLE
[styletron-utils] Support transformation middlewares

### ISSUE THREAD

**Issue by umidbekkarimov** [styletron/styletron#39]
As an example - [jss](https://github.com/cssinjs/jss) has [plugins](https://github.com/cssinjs/jss/blob/master/docs/plugins.md) to modify styles before injecting them.

### My Proposal

Add `injectStyle` creator - that will accept `transformer` function as it's first argument

```javascript
export function createInjectStyle(transform) {
  return function injectStyle(styletron, styles, media, pseudo) {
     // transformations
  }
}
```

And first `injectStyle` with transfromer would be `injectStylePrefixed`:

```javascript
export const injectStylePrefixed = createInjectStyle(() => /* add prefixes */) 
``` 

Also every lib that use `styletron-utils` should have an option to pass custom `injectStyle` functions.

e.g. `styletron-react` :

```javascript
const injectStyles = createInjectStyle(compose(...myTransformers))

ReactDOM.render(
  <StyletronProvider
    injectStyles={injectStyles} 
    styletron={new Styletron(styleElements)}>
    <App/>
  </StyletronProvider>
);
```

**Comment by rtsao** [comment]
I think a middleware concept is a great idea!

The reason I implemented injectStyle and injectStylePrefixed separately is in the prefixed case I can avoid a lot of object instantiation overhead by iterating and making injectDeclaration calls rather than creating new style objects. With vendor prefixing, this turned out to have some measurable impact. So I think in specialized cases it will probably be faster to implement a single function that does everything you need, but a `createInjectStyle` helper would be a nice way to do it in a more modular fashion.

**Comment by umidbekkarimov** [comment]
@rtsao had bad time with `lerna` last night 😅 today I will try again.

**Comment by vikfroberg** [comment]
We had a use case for a rtl middleware which uses react context to know if it's rtl or not. So for us createInjectStyle would be to low level, it would make more sense to put the middleware in styletron-react in our case.

**Comment by faddee** [comment]
Someone working on this? Can I assist in any way?

**Comment by faddee** [comment]
Pull #91

**Comment by rtsao** [comment]
There's now a means for customizing the injection logic. For context, check out:

https://github.com/rtsao/styletron/pull/127
https://github.com/rtsao/styletron/pull/91#pullrequestreview-34732010

So now we could explore adding another export in `styletron-react` with a plugin/middleware interface

What should the plugin API be? A random idea:

```js
import {styled, applyPlugin} from 'styletron-react';
import defaultUnits from 'styletron-plugin-default-units';

applyPlugin(styled, defaultUnits); // now `styled` will use the default units plugin globally
```

**Comment by rtsao** [comment]
I like the idea of middlewares provided the following condition is met:
- Without the middlewares, the styles are still valid

LTR-to-RTL and vendor prefixing fit this category

**Comment by rtsao** [comment]
I think this issue has been resolved.
