### ISSUE TITLE
Which one is deprecated, `withStyle` or `withStyleDeep`?

### ISSUE THREAD

**Issue by SukkaW** [styletron/styletron#416]
[The documentation says](https://www.styletron.org/api-reference):

> `withStyleDeep` has been deprecated in v5 of Styletron. `withStyle` now performs a deep object merge by default as this was what was generally desired.

However, the source code indicates that it is `withStyle` that are being aliased to `withStyleDeep`:

https://github.com/styletron/styletron/blob/16d0f494989aa26ce88eac715315860995d58b28/packages/styletron-react/src/index.js#L225

Also, the `@types/styletron-react` (which is not maintained by the styletron team anyway) marks `withStyle` is deprecated:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/512de0ac72aa62e7e048aa2ff9fc0c09944ad8b6/types/styletron-react/index.d.ts#L161-L165

So, which one I should use? `withStyle` or `withStyleDeep`?

**Comment by tajo** [comment]
You should use `withStyle`.

**Comment by SukkaW** [comment]
> You should use `withStyle`.

Thanks!
