### ISSUE TITLE
Media queries stopped working in atomic engine 1.6.0

### ISSUE THREAD

**Issue by mlmmn** [styletron/styletron#438]
As in the subject. Below you'll find simple sandbox where you can downgrade engine to 1.5.0 which makes styles work as expected

https://codesandbox.io/s/morning-cookies-8c9hzx?file=/src/App.tsx

**Comment by LukeSheard** [comment]
I have also found this with 1.6.0 as well!

**Comment by rtsao** [comment]
I've reverted https://github.com/styletron/styletron/commit/d180f0ce6115e5048e1b60d13788fc5fdabfbdd3 and published a new version at 1.6.1 for the time being. Probably something do do with: https://github.com/styletron/styletron/pull/437/files#r1343096955

**Comment by LukeSheard** [comment]
@rtsao I think you can see from the tests [here](https://github.com/styletron/styletron/pull/437/files#diff-22bb5d8b14764213de931655864cf2faa01b6cf4be0c6f811096fdd9bf0cb359R41) that the media attribute is being incorrectly pulled through. I think where ever it was being removed before just needs to be migrated to wherever that media attribute is pulled back out.
