### ISSUE TITLE
Is 1.6.1 published correctly?

### ISSUE THREAD

**Issue by simPod** [styletron/styletron#439]
I'm getting 

> TS7016: Could not find a declaration file for module 'styletron-engine-atomic'.

with 1.6.1. 

1.6.0 works ok.

I see a lot of tests exported and a lot of .d.ts removals https://app.renovatebot.com/package-diff?name=styletron-engine-atomic&from=1.6.0&to=1.6.1

**Comment by mlmmn** [comment]
I noticed this as well, looks like `lib` dir (that contains declaration files) was not included in the package

**Comment by rtsao** [comment]
Published 1.6.2 with `/lib` files

**Comment by simPod** [comment]
@rtsao Also, IMO tests files should be excluded as it only increases artifact size

https://app.renovatebot.com/package-diff?name=styletron-engine-atomic&from=1.6.0&to=1.6.2
