### ISSUE TITLE
Vue support?

### ISSUE THREAD

**Issue by adalberth** [styletron/styletron#76]
Is it possible to support Vue?

**Comment by rtsao** [comment]
I haven't had the chance to use Vue personally, but I think it should definitely be possible since Styletron is very un-opinionated. Definitely something worth exploring!

**Comment by sebastianmacias** [comment]
+1

**Comment by rtsao** [comment]
I just found this: https://github.com/LostCrew/vue-styletron

**Comment by ephor** [comment]
[https://github.com/LostCrew/vue-styletron/issues/1](url) Can somebody help me with this problem? Unfortunately its work only with object style

**Comment by egoist** [comment]
Just made https://github.com/egoist/styletron-vue, same usage as in styletron-react

**Comment by SumeetGohil** [comment]
+1

**Comment by rtsao** [comment]
I think this can be marked as resolved. Thanks!
