### ISSUE TITLE
Ecosystem?

### ISSUE THREAD

**Issue by jbellsey** [styletron/styletron#88]
Hi - we're working on a package that improves the ergonomics of using Styletron in a large React app. Do you have a list of links, or another way to share Styletron-related projects?

**Comment by rtsao** [comment]
Good idea, I can add a section to the docs/README!

**Comment by jbellsey** [comment]
FYI - we just (months later!) published our code:

  https://github.com/lookout/styletron-themer/

There are a few other notable projects emerging in the Styletron ecosystem, just search on NPM and you'll see some interesting ones. I'd love to keep raising visibility so Styletron remains an appealing lib for people using CSS-in-JS!

**Comment by rtsao** [comment]
Doing a bit of GitHub cleanup and I think we can close this now. Thanks!
